version: "3.4"

services:
  postgres:
    container_name: movies-db
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: movies
      POSTGRES_PASSWORD: movies

volumes:
  postgres_data: