version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: nityam@1492
      POSTGRES_DB: Movie
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgre:nityam@1492@postgres:5432/Movie
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
